apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  annotations:
    wave.pusher.com/update-on-config-change: "true"
  labels:
    app: ${name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: test
                key: foo
